hackathon_sku_2team_backend/urls.py
from django.contrib import admin
from django.urls import path , include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

# swagger 엔드포인트
schema_view = get_schema_view( 
    openapi.Info( 
        title="Swagger Study API", 
        default_version="v1", 
        description="Swagger Study를 위한 API 문서", 
        terms_of_service="https://www.google.com/policies/terms/", 
        contact=openapi.Contact(name="test", email="test@test.com"), 
        license=openapi.License(name="Test License"), 
    ), 
    public=True, 
    permission_classes=(permissions.AllowAny,), 
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('see_near.urls')),
    
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    #path('see_near/', include('see_near.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

see_near/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

from rest_framework import routers

router = routers.DefaultRouter() # DefaultRouter를 설정
router.register(r'Post', views.PostViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'comments', views.CommentViewSet)
router.register(r'carts', views.CartViewSet)
router.register(r'cart-items', views.CartItemViewSet)
router.register(r'users', views.SeenearUserViewSet)


urlpatterns = [
    # 게시물
    path('', views.product_list, name = 'home'),
    path('create_post/', views.create_post, name = 'create_post'),
    path('post_detail/<int:post_id>/', views.product_detail, name='post_detail'),
    path('main/edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('main/delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('search/', views.search, name='search'),
    path('category/<int:category_id>/', views.category_view, name='category'),
    # 댓글
    path('coment/<int:comment_id>/edit/', views.comment_edit, name='comment_edit'),
    path('comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    # 장바구니
    path('post_detail/add_cart/<int:post_id>/', views.add_cart, name='add_cart'),
    path('post_detail/minus_cart/<int:post_id>/', views.minus_cart, name='minus_cart'),
    path('post_detail/remove_selected/', views.remove_selected, name='remove_selected'),
    path('post_detail/cart/', views.cart_detail, name='cart_detail'), 
    # 결제
    path('cart/payment/', views.payment, name='payment'),
    # 회원가입/로그인
    path('register/', views.register, name='register'),
    path('login/', views.login_sn, name='login'),
    path("logout/", views.logout_view, name='logout'),
    path('user_page/<int:pk>/', views.user_page, name='user_page'),
    path('update_user/<int:pk>/', views.update_user, name='update_user'),
    # swagger api
    path('', include(router.urls))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

see_near/models.py
from datetime import timezone
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser, AbstractBaseUser
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model
from mptt.models import MPTTModel, TreeForeignKey
        
class SeenearUserManager(BaseUserManager):
    def create_user(self, user_id, email, nickname, full_name, password, address, Inputname, staff=False, admin=False, active=True):
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.user_id = user_id
        user.nickname = nickname
        user.full_name = full_name
        user.staff = staff
        user.admin = admin
        user.address = address
        user.Inputname = Inputname
        user.active = active
        user.save(using=self._db)
        
        
        return user

    def create_superuser(self, user_id, email, nickname, full_name, password, address, Inputname):
        user = self.create_user(
            user_id,
            email,
            nickname,
            full_name,
            password,
            address,
            Inputname,
            staff = True,
            admin = True
            
        )
        
        return user


class seenear_user(AbstractBaseUser):  
    user_id = models.CharField(max_length=200, unique=True)     # id
    nickname = models.CharField(max_length=255, blank=True)     # nickname
    email = models.EmailField(max_length=255, null=True)   # email
    full_name = models.CharField(max_length=100)                # 이름
    address = models.TextField(max_length=200, null=True)       # 주소
    Inputname = models.TextField(max_length=200, null=True)       # 주소
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['nickname', 'full_name', 'email', 'address', 'Inputname']
    objects = SeenearUserManager()
    
    def __str__(self):
        return self.user_id

    def has_perm(self, perm, obj=None):
        return self.admin

    def has_module_perms(self, app_label):
        return self.admin

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_superuser(self):
        return self.admin


# 카테고리
class Category(MPTTModel):
    name = models.CharField(max_length=100)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    image = models.ImageField(upload_to='category_images/', blank=True)
    
    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name

# 게시물
class Post(models.Model):
    post_id = models.AutoField(primary_key=True) #게시물 아이디
    title = models.CharField(max_length=100) # 제목
    name = models.CharField(max_length=100)  # 제품명
    content = models.TextField()  # 내용
    price = models.IntegerField() # 가격
    situation = models.CharField(max_length=200, default="판매중") # 거래 상황
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    seller = models.ForeignKey(seenear_user, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    images = models.ImageField(blank=True, upload_to="images/", null=True) # 업로드된 이미지파일을 이미지에 저장
    
    def __str__(self):
        return self.title

# 댓글
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    nickname = models.ForeignKey(seenear_user, on_delete=models.CASCADE)
    content = models.TextField()
    C_pub_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.nickname.full_name}의 댓글"

# 장바구니 모델
class Cart(models.Model):
    cart_id=models.CharField(max_length=250, blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
        
    def __str__(self):
        return self.cart_id

    
class CartItem(models.Model):
    product=models.ForeignKey(Post, on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CarItem'
        
    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return self.product

see_near/views.py
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from .forms import ProductForm
from .models import Category, Post, Cart, CartItem, seenear_user, Comment
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.core.paginator import Paginator

from rest_framework import viewsets
from .serializers import (
    CategorySerializer, PostSerializer, CommentSerializer,
    CartSerializer, CartItemSerializer, SeenearUserSerializer
)
from drf_yasg.utils import swagger_auto_schema
from rest_framework.permissions import IsAuthenticated

from django.conf import settings


# 메인 화면(상품 정보를 전달하는 함수)
def product_list(request):
    products = Post.objects.all()
    sort_by = request.GET.get('sort', 'name')
    category_id = request.GET.get('category')
    
    if request.method == "POST":
        if request.POST.get('category'):
            category_get = get_object_or_404(Category, id=request.POST.get('category'))
            
            return redirect('category', category_id=category_get.id)
        
    if category_id:
        category = get_object_or_404(Category, pk=category_id)
        products = Post.objects.filter(categories=category)
    
    if sort_by == 'name':
        products = Post.objects.order_by('title')
    elif sort_by == 'date':
        products = products.order_by('-pub_date')
        
    searched = request.GET.get('searched', '')
    if searched:
        products = products.filter(title__icontains=searched)
        
    paginator = Paginator(products, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    categories = Category.objects.all()
    
    context = {
        'products':products,
        'categories':categories,
        'searched':searched,
        'page_obj':page_obj
    }
    
    return render(request, 'see_near/Main.html', context)

# 상품 상세정보
def product_detail(request, post_id):
    post = get_object_or_404(Post, post_id=post_id)
    comments = Comment.objects.filter(post=post)
    comment_count = comments.count()
    
    if request.method == 'POST':
        if request.user.is_authenticated:
            user_instance = request.user
            content = request.POST.get('content', '').strip()

            if content:
                post_instance = Post.objects.get(pk=post.pk)
                comment = Comment(post=post_instance, nickname=user_instance, content=content)
                comment.save()
                return redirect('post_detail', post_id=post_id)
            
    return render(
        request,
        'see_near/post_detail.html', 
        {'post': post, 'comments': comments, 'comment_count': comment_count}
    )

# 카테고리 분류 함수
def category_view(request, category_id):
    selected_category = Category.objects.get(pk=category_id)
    category_posts = Post.objects.filter(categories=selected_category)
    
    paginator = Paginator(category_posts, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'selected_category_id': selected_category,
        'category_posts': category_posts,
        'page_obj':page_obj
    }

    return render(request, 'see_near/category.html', context)

# 게시물 생성
@login_required
def create_post(request):
    if request.method == "POST":
        title = request.POST['title']
        name = request.POST['name']
        content = request.POST['content']
        price = request.POST['price']
        situation = request.POST.get('situation', "판매중")  # 기본값 설정
        category_id = request.POST['category']
        images = request.FILES['image'] if 'image' in request.FILES else None
        
        try:
            category = Category.objects.get(pk=category_id)
        except Category.DoesNotExist:
            pass
        
        post = Post(
            title=title,
            name=name,
            content=content,
            price=price,
            situation=situation,
            categories=category,
            seller=request.user,
            images=images
        )
        post.save()

        return redirect('home')
    else:
        categories = Category.objects.all()

    return render(request, 'see_near/create_post.html', {'categories': categories})


# 게시글 수정
@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, post_id=post_id)
    print(post.seller)
    
    if request.user == post.seller:  # 로그인한 사용자와 게시물 작성자 비교
        if request.method == "POST":
            form = ProductForm(request.POST, request.FILES, instance=post)

            if form.is_valid():
                form.save()
                return redirect('home')
        else:
            form = ProductForm(instance=post)
        return render(request, 'see_near/edit_post.html', {'form': form, 'post': post})
    else:
        return redirect('home')  # 권한이 없는 경우 홈 화면으로 리다이렉트

# 게시글 삭제
@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    print(post.seller)
    
    if post.seller == request.user:
        if request.method == "POST":
            post.delete()
            return redirect('home')
    else:
        return HttpResponseForbidden("You do not have permission to delete this post.")
    
    context = {'post': post}
    return render(request, 'see_near/delete_post.html', context)

# 댓글 수정
@login_required
def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    
    if request.method == 'POST':
        comment.content = request.POST.get('content', '').strip()
        comment.save()
        return redirect('post_detail', post_id=comment.post.pk)
        
    return render(request, 'see_near/comment_edit.html', {'comment': comment})


# 댓글 삭제
@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    
    if request.method == 'POST':
        post_pk = comment.post.pk  # Store the post pk before deleting the comment
        comment.delete()
        return redirect('post_detail', post_id=post_pk)  # Redirect to the correct post detail page
    
    return render(request, 'see_near/comment_delete.html', {'comment': comment})


# 검색창
def search(request):
    if request.method =='POST':
        searched = request.POST['searched']
        products = Post.objects.filter(title__contains=searched)
        
        paginator = Paginator(products, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        return render(request, 'see_near/search.html', {'searched':searched, 'products':products, 'page_obj':page_obj})
    else:
        return render(request, 'see_near/search.html')
    
    
#--------------------여기부턴 장바구니에요--------------------

# 카트 저장하는 함수
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request, post_id): #카트에 저장 후 카트 페이지로 넘어감(이 아이로 넘겨줘야 함)
    product=Post.objects.get(pk=post_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=cart_id(request))
        cart.save()
        
    try:
        cart_item=CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
        
    return redirect('cart_detail')

def minus_cart(request, post_id):
    product=Post.objects.get(pk=post_id)
    
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=cart_id(request))
        cart.save()
        
    try:
        cart_item=CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity >= 2:
            cart_item.quantity -= 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
        
    return redirect('cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None, selected=None): #카트 페이지 정보
    try:
        selected = request.POST.getlist('selected')
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    
    return render(request, 'see_near/cart.html', dict(cart_items=cart_items, total=total, counter=counter, selected=selected))

def remove_selected(request):
    if request.method =="POST":
        selected_items=request.POST.getlist('selected')
        cart=Cart.objects.get(cart_id=cart_id(request))
        
        for item_id in selected_items:
            cart_item=get_object_or_404(CartItem, id=item_id)
            if cart_item.cart ==cart:
                cart_item.delete()
                
    return redirect('cart_detail')

#--------------------여기부턴 유저관리

# 회원가입
def register(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        email = request.POST.get('email')
        nickname = request.POST.get('nickname')
        full_name = request.POST.get('full_name')
        password = request.POST.get('password')
        address = request.POST.get('address')
        Inputname = request.POST.get('Inputname')
        
        # 아이디 중복 확인

see_near/templates/see_near/backend/cart.html
<!DOCTYPE>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>장바구니</title>
    <link href="{% static 'see_near/bootstrap/bootstrap.min.css'%}" rel="stylesheet"/>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></script>
    <!-- iamport.payment.js -->
    <script type="text/javascript" src="https://cdn.iamport.kr/js/iamport.payment-1.2.0.js"></script>
    <script>
        var IMP = window.IMP; 
        IMP.init("imp53883146");

        {% comment %} var productName = "{{ cart_items.product.name }}"; {% endcomment %}
        var productName="good";
        var counter="{{ counter }}";
        var total="{{ total }}"; 

        var today = new Date();   
        var hours = today.getHours(); // 시
        var minutes = today.getMinutes();  // 분
        var seconds = today.getSeconds();  // 초
        var milliseconds = today.getMilliseconds();
        var makeMerchantUid = hours +  minutes + seconds + milliseconds;
        

        function requestPay() {
            IMP.request_pay({
                pg : 'kcp',
                pay_method : 'card',
                merchant_uid: "IMP"+makeMerchantUid, 
                name : productName,
                amount : total,
                buyer_email : 'Iamport@chai.finance',
                buyer_name : '아임포트 기술지원팀',
                buyer_tel : '010-1234-5678',
                buyer_addr : '서울특별시 강남구 삼성동',
                buyer_postcode : '123-456'
            }, function (rsp) { // callback
                if (rsp.success) {
                    console.log(rsp);
                } else {
                    console.log(rsp);
                }
            });
        }
    </script>
</head>
<body>
    <h1>장바구니</h1>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <form method="post" action="{%url 'remove_selected'%}">
            {% csrf_token %}
            <table class="table my_custom_table">
                <thread class="my_custom_table">
                    <tr>
                        <th colspan="5">
                            Your items
                        </th>
                    </tr>
                </thread>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <input id="selected" type="checkbox" name="selected" value="{{ cart_item.id }}">
                        </td>
                        <td>
                            <a href="{{ cart_item.product.get_absolute_url }}"><img src="{{ cart_item.product.images.url }}" alt="" class="float-left rounded custom_image"></a>
                        </td>
                        <td class="text-align">
                            {{cart_item.product.title}}
                            <br>
                            id: {{cart_item.product.post_id}}
                            <br>
                            price: {{cart_item.product.price}}원
                            <br>
                            quantity: {{cart_item.quantity}}개
                            {% if cart_item.quantity <= counter %}
                            {% comment %} <a href="{% url 'add_cart' cart_item.product.post_id %}" class="custom_a">
                                <i class="fas fa--plus-circle custom_icon"></i>
                                </a> {% endcomment %}
                                <a href="{% url 'minus_cart' cart_item.product.post_id %}"><p>수량빼기</p></a>
                                <a href="{% url 'add_cart' cart_item.product.post_id %}"><p>수량더하기</p></a>
                            {% else %}
                            {% endif %}
                        </td>
                        <td>
                            total: {{cart_item.sub_total}}원
                        </td>    
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="submit">선택한 항목 삭제</button>
        </form>
        </div>
        <div class="col-12 col-sm-21 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thread class="my_custom_thread">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thread>
                <tbody>
                    <tr>
                        <td>
                            결제 금액
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            총 개수: <b>{{ counter }}개</b> 총 가격: <b>{{ total }}원</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <button class='btn btn-outline-success' onclick="requestPay()">결제</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

see_near/templates/see_near/backend/category.html
<!DOCTYPE html>
<html>
<head>
    <title>Posts by Category</title>
</head>
<body>
    <h1>Posts in {{ selected_category.name }}</h1>
    <ul>
        {% for post in category_posts %}
            <li>{{ post.title }}</li>
        {% endfor %}
    </ul>
</body>
</html>

see_near/templates/see_near/backend/comment_delete.html
<h3>댓글 삭제</h3>
<p>정말로 이 댓글을 삭제하시겠습니까?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">삭제</button>
</form>

see_near/templates/see_near/backend/create_post.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>Write a Post</title>
	<link rel="stylesheet" href="{% static 'see_near/bootstrap/bootstrap.min.css' %}">
</head>
<body>
	<h1>판매 상품 등록</h1>
	<hr>
	<form method='post' enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tbody>
			{% comment %} <select name="p_category" required>
				{% for category in categories %}
					<option value="{{ category.id }}">{{ category.name }}</option>
				{% endfor %}
			</select> {% endcomment %}
        	{{form.as_p}}
				{% comment %} <tr>
					<th><label for="id_product">Title:</label></th>
					<td><input type="text" name="title" maxlength="30" required="" id="id_todo"></td>
				</tr>
				<tr>
					<th><label for="id_product">Price:</label></th>
					<td><input name="price" cols="40" rows="10" required="" id="id_price"></input></td>
				</tr>
        <tr>
					<th><label for="id_product">Categories:</label></th>
					<td><input name="price" cols="40" rows="10" required="" id="id_price"></input></td>
				</tr>
        <tr>
					<th><label for="id_product">Content:</label></th>
					<td><input name="price" cols="40" rows="10" required="" id="id_price"></input></td>
				</tr>
        <tr>
					<th><label for="id_product">Image:</label></th>
					<td><input type="file" class="form-control" name="imgfile" id="imgfile"></td>
				</tr> {% endcomment %}
				</tbody>
			</table>
			<button type="submit" class="btn btn-primary" style="margin-left: 350px;">Submit</button>
	</form>
</body>
</html>

see_near/templates/see_near/backend/edit_post.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Post</title>
</head>
<body>
    <h1>Edit Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

see_near/templates/see_near/backend/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>상품 띄우기</title>
        <link href={% static "see_near/bootstrap/bootstrap.min.css"%} rel="stylesheet" />
        <link href="css/style.css" rel="stylesheet"/>
        <!-- responsive style -->
        <link href="css/responsive.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <ul>
                {% if request.user.is_authenticated %}
                <!-- 로그인한 경우: 로그아웃 버튼과 회원정보 수정 버튼 표시 -->
                <a href ="{% url 'logout' %}">로그아웃</a>
                <li class="nav-item"><a class="nav-link" href="create_post/">게시물</a></li>
                <li class="nav-item"><a href="{% url 'cart_detail' %}">장바구니</a></li>
                <a href="{% url 'payment'%}"><button type="button">상품 구매</a></button>
                <a href="{% url 'update_user' user.pk %}"><button type="button">회원정보 수정</a></button>
                {% else %}
                <!-- 로그인하지 않은 경우: 로그인 버튼 표시 -->
                <a href="{% url 'login' %}">로그인</a>
                <a href="{% url 'register' %}">회원가입</a>
                {% endif %}
            </ul>
            <form class="d-flex" method="POST" action="{% url 'search' %}">
              {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <section class="shop_section layout_padding">
                <div class="container">
                  {% for category in categories %}
                  <form action="{% url 'category' category_id=category.pk %}" method="post" style="display: inline;">
                      {% csrf_token %}
                      <input type="hidden" name="category" value="{{ category.pk }}">
                      <button type="submit" class="btn btn-primary">{{ category.name }} Filter</button>
                  </form>
                  {% endfor %}  
                  
                  <form>
                    {% csrf_token %}
                    <label for="sort_by">Sort By:</label>
                    <select name="sort" id="sort_by">
                        <option value="name" {% if sort_by == 'name' %}selected{% endif %}>이름순</option>
                        <option value="date" {% if sort_by == 'date' %}selected{% endif %}>최신순</option>
                    </select>
                    <button type="submit" class="btn btn-primary">Sort Filter</button>
                  </form>
                  
                  <div class="heading_container heading_center">
                    <h2>
                    Latest Products
                    </h2>
                  </div>
                  <div class="row">
                    {% for product in products %}
                    <div class="col-sm-6 col-md-4 col-lg-3">
                      <div class="box">
                        <a href="{% url 'post_detail' product.post_id %}">
                          <div class="img-box">
                            <img class="card-img-top embed-responsive-item" src="{{ product.images.url }}" width="100" alt="images/" />
                          </div>
                          <div class="detail-box">
                            <h6>
                                {{ product.title }}
                            </h6>
                            <h6>
                              Price
                              <span>
                                {{ product.price }}
                              </span>
                            </h6>
                          </div>
                          <div class="new">
                            <span>
                              New
                            </span>
                          </div>
                        </a>
                      </div>
                    </div>
                    {% endfor %}
                </div>
              </section>
            
        </div>
    </body>
</html>

see_near/templates/see_near/backend/user_update.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
   <meta charset="UTF-8">
   <title>회원정보 수정</title>
</head>
<body>
   <h1>회원정보 수정</h1>
   <hr/>
   <form method='post' enctype="multipart/form-data">
      {% csrf_token %}
    <table>
        <tbody>
            <tr>
                <th><label for="id_full_name">성함:</label></th>
                <td><input type="text" name="full_name" maxlength="30" required="" id="id_full_name" value="{{ user.full_name }}"></td>
            </tr>
            <tr>
                <th><label for="id_email">Email:</label></th>
                <td><input type="email" name="email" maxlength="30" required="" id="id_email" value="{{ user.email }}"></td>
            </tr>
            <tr>
                <th><label for="id_nickname">Nickname:</label></th>
                <td><input type="text" name="nickname" maxlength="30" required="" id="id_nickname" value="{{ user.nickname }}"></td>
            </tr>
            <tr>
                <th><label for="id_user_id">User ID:</label></th>
                <td><input type="text" name="user_id" maxlength="30" required="" id="id_user_id" value="{{ user.user_id }}"></td>
            </tr>
            <tr>
                <th><label for="id_password">Password:<br>(비밀번호는 *로 길게 나타납니다.)</label></th>
                <td><input type="password" name="password" maxlength="30" required="" id="id_password" value="{{ user.password }}"></td>
            </tr>
        </tbody>
    </table>
    <button type="submit" class="btn btn-primary" style="margin-left: 350px;">수정</button>
</form>
</body>
</html>